// ROM data automatically generated by generate-rom-data-files.js
// Source: GLABIOS_0.2.5_8E.rom

#ifndef YAX86_BIOS_ROM_DATA_H
#define YAX86_BIOS_ROM_DATA_H

#include <stdint.h>

enum {
  kBIOSROMDataSize = 8192,
};

// A data declaration has no spelling that works in both configurations,
// so this one is visible only when unbundled. `extern` is what an
// unbundled caller needs, and conflicts with the static definition once
// bundled. The bundled build reaches the array by position instead, so
// the generated source precedes its users in bundle.json.
#ifndef YAX86_BIOS_BUNDLE_H
extern const uint8_t kBIOSROMData[kBIOSROMDataSize];
#endif // YAX86_BIOS_BUNDLE_H

#endif // YAX86_BIOS_ROM_DATA_H
