// ROM data automatically generated by generate-rom-data-files.js
// Source: XTIDE_Universal_BIOS_XT_r631.rom

#ifndef YAX86_HDC_OPTION_ROM_DATA_H
#define YAX86_HDC_OPTION_ROM_DATA_H

#include <stdint.h>

enum {
  kHDCOptionROMDataSize = 12288,
};

#ifndef YAX86_HDC_BUNDLE
extern const uint8_t kHDCOptionROMData[kHDCOptionROMDataSize];
#endif // YAX86_HDC_BUNDLE

#endif // YAX86_HDC_OPTION_ROM_DATA_H
