// ROM data automatically generated by generate-rom-data-files.js
// Source: XTIDE_Universal_BIOS_XT_r631.rom

#ifndef YAX86_HDC_OPTION_ROM_DATA_H
#define YAX86_HDC_OPTION_ROM_DATA_H

#include <stdint.h>

enum {
  kHDCOptionROMDataSize = 12288,
};

// In unbundled builds, external callers within the module need an extern
// declaration. In bundled builds, the array is static and defined earlier in
// the same translation unit (via bundle.json), so an extern declaration
// would conflict and is omitted.
#ifndef YAX86_HDC_BUNDLE_H
extern const uint8_t kHDCOptionROMData[kHDCOptionROMDataSize];
#endif // YAX86_HDC_BUNDLE_H

#endif // YAX86_HDC_OPTION_ROM_DATA_H
