// BIOS ROM data automatically generated by generate-bios-rom-data-files.js
// Source: GLABIOS_0.2.5_8E.rom

#ifndef YAX86_BIOS_ROM_DATA_H
#define YAX86_BIOS_ROM_DATA_H

#include <stdint.h>

enum {
  kBIOSROMDataSize = 8192,
};

#ifndef YAX86_BIOS_BUNDLE
extern const uint8_t kBIOSROMData[kBIOSROMDataSize];
#endif // YAX86_BIOS_BUNDLE

#endif // YAX86_BIOS_ROM_DATA_H
